#!/bin/bash
# 
# This file is part of PoelderBash
# Copyright (c) 2016-2019 Amos Brocco.
# 
# This program is free software: you can redistribute it and/or modify  
# it under the terms of the GNU General Public License as published by  
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but 
# WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License 
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

set -f # disable globbing in strings
# ======================================================================
# Configuration parameters
# ======================================================================
PIDFILE=/tmp/poelderpid
THISPID=$$
PORT=8183
GAMESTATEFILE=/tmp/.poelderbash.state
GAMESTATEFILELOCK=/tmp/poelderbash.lock 
PLAYERLOOKFILE=/tmp/poelderlooktmp
PLAYERSAYFILE=/tmp/poeldersaytmp
PLAYERINFOFILE=/tmp/poelderpostmp
PLAYERPERSONAFILE=/tmp/poelderpersona
PLAYERCMDFILE=/tmp/poelderplayercmd
SAVEGAMEFILE=/tmp/poeldersavegame
